apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../base

namespace: demo

images:
  - name: ghcr.io/hai2rams/gitops-hello
    newName: ghcr.io/hai2rams/gitops-hello
    newTag: "c51327ddf304f53812704b8c035aa36f730a7372"