resources:
  - namespace.yaml
  - ../../base

namespace: demo

images:
    - name: ghcr.io/hai2rams/gitops-hello:dev
<<<<<<< HEAD
    newName: ghcr.io/hai2rams/gitops-hello
    newTag: "3dc33a487b6c1673ada73824adbb6436b809b29c"
=======
      newName: ghcr.io/hai2rams/gitops-hello 
      newTag: "dev"
>>>>>>> 6e834fa (fourth commit)
